// Stable recording IDs: add the matching CDN URL to englishMedia when ready.
// Isolated phonemes deliberately live outside this TTS script.
export const englishNarration: Record<string, string> = {
  'word-pan': 'pan',
  'word-tap': 'tap',
  'story-pan': 'This is a pan.',
  'story-tap': 'Tap the table.',
  'discover-read': 'Your turn to read.',
  'discover-help': 'Let’s read it together.',
  'discover-build': 'Listen. Make the word.',
  'discover-build-help': 'Try this sound.',
  'discover-retry': 'Listen again.',
  'discover-read-back': 'Read your word.',
  'discover-next': 'Let’s try another word.',
  'discover-finish': 'Two more words. Well done!',
  'intro-listen': 'Let’s listen together.',
  'intro-try': 'Now you try.',
  'build-intro-pin': 'Let’s make a word together.',
  'build-intro-sit': 'Let’s make a word together.',
  'word-pin': 'pin',
  'word-sit': 'sit',
  'say-pin': 'Say pin.',
  'say-sit': 'Say sit.',
  'say-again-pin': 'Say pin one more time.',
  'say-again-sit': 'Say sit one more time.',
  'read-done-pin': 'Let’s see what it means.',
  'read-done-sit': 'Let’s see what it means.',
  'story-pin': 'This is a pin.',
  'story-sit': 'Sit on the mat.',
  'celebrate-pin': 'You made pin. Well done!',
  'celebrate-sit': 'You made sit. Well done!',
  'more-review-intro': 'Let’s play with our new words.',
  'review-find-pin': 'This is a pin. Find pin.',
  'review-find-sit': 'Sit on the mat. Find sit.',
  'review-correct-pin': 'You found pin!',
  'review-correct-sit': 'You found sit!',
  'cases-big-s': 'Tap big S.',
  'cases-small-s': 'Now tap small s.',
  'cases-big-a': 'Tap big A.',
  'cases-small-a': 'Now tap small a.',
  'cases-big-t': 'Tap big T.',
  'cases-small-t': 'Now tap small t.',
  'cases-same-sound': 'Same letter. Same sound.',
  'paper-watch': 'Watch.',
  'paper-watch-again': 'Watch again.',
  'paper-write-big-s': 'Your turn. Write big S.',
  'paper-write-small-s': 'Your turn. Write small s.',
  'paper-write-big-a': 'Your turn. Write big A.',
  'paper-write-small-a': 'Your turn. Write small a.',
  'paper-write-big-t': 'Your turn. Write big T.',
  'paper-write-small-t': 'Your turn. Write small t.',
  'paper-one-more': 'Let’s try one more.',
  'paper-own-turn': 'Try one on your own.',
  'link-listen': 'Listen.',
  'link-find': 'Listen. Find it.',
  'link-find-it': 'Find it.',
  'link-touch': 'Tap and say.',
  'link-your-turn': 'Your turn.',
  'link-retry': 'Listen again.',
  'link-help': 'Let’s listen together.',
  'practice-watch': 'Watch.',
  'practice-watch-again': 'Watch again.',
  'practice-now-try': 'Now you try.',
  'practice-your-turn': 'Your turn.',
  'practice-listen': 'Listen.',
  'build-intro-at': 'Let’s make a word together.',
  'build-intro-sat': 'Let’s make a word together.',
  'build-tap': 'Now tap',
  'build-next-tap': 'Now tap',
  'build-find': 'Find this sound.',
  'build-next': 'Now find this sound.',
  'build-ready': 'Put the sounds together.',
  'build-retry': 'Try this sound.',
  'build-hint': 'Tap this letter.',
  'build-own-at': 'Can you make at?',
  'build-own-sat': 'Can you make sat?',
  'word-at': 'at',
  'word-sat': 'sat',
  'say-at': 'Say at.',
  'say-sat': 'Say sat.',
  'say-again-at': 'Say at one more time.',
  'say-again-sat': 'Say sat one more time.',
  'read-turn': 'Your turn. Try reading it.',
  'read-again': 'Let’s read it once more.',
  'read-watch': 'Watch and say it with me. Then try again.',
  'read-done-sat': 'Let’s see what it means.',
  'read-done-at': 'Let’s see what it means.',
  'story-at': 'Sam is at the door.',
  'story-sat': 'Sam sat on the mat.',
  'question-mat': 'Sam sat on the mat. Tap the picture.',
  'question-bench': 'Sam sat on the bench. Tap the picture.',
  'meaning-correct': 'You found it!',
  'meaning-retry': 'Who sat down?',
  'celebrate-sat': 'You made sat. Well done!',
  'celebrate-at': 'You made at. Well done!',
  'review-intro': 'Let’s play with our first words.',
  'review-listen': 'Tap each word to listen.',
  'review-find-at': 'Sam is at the door. Find at.',
  'review-find-sat': 'Sam sat on the mat. Find sat.',
  'review-correct-at': 'You found at!',
  'review-correct-sat': 'You found sat!',
  'review-retry': 'Try again.',
  'review-read': 'Your turn to read.',
  'review-read-next': 'Read this word.',
  'review-finish': 'Two words. Well done!',
};

export type EnglishAudioCue = { id: string; narration?: string; optional?: boolean };
// Instructions may fail on devices without TTS; still play the real phoneme.
export const narrationCue = (id: string): EnglishAudioCue => ({ id, narration: englishNarration[id], optional: true });
